export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧', locale: 'en-US', articles: [] },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', locale: 'es-ES', articles: ['el', 'la', 'los', 'las'] },
  { code: 'fr', name: 'French', flag: '🇫🇷', locale: 'fr-FR', articles: ['le', 'la', 'les'] },
  { code: 'de', name: 'German', flag: '🇩🇪', locale: 'de-DE', articles: ['der', 'die', 'das'] },
  { code: 'zh', name: 'Mandarin Chinese', flag: '🇨🇳', locale: 'zh-CN', articles: [] },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', locale: 'ja-JP', articles: [] },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', locale: 'ko-KR', articles: [] },
  { code: 'it', name: 'Italian', flag: '🇮🇹', locale: 'it-IT', articles: ['il', 'lo', 'la', 'i', 'gli', 'le'] },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹', locale: 'pt-PT', articles: ['o', 'a', 'os', 'as'] },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', locale: 'ru-RU', articles: [] },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', locale: 'hi-IN', articles: [] },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷', locale: 'tr-TR', articles: [] },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱', locale: 'nl-NL', articles: ['de', 'het'] },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪', locale: 'sv-SE', articles: ['en', 'ett'] },
  { code: 'pl', name: 'Polish', flag: '🇵🇱', locale: 'pl-PL', articles: [] },
  { code: 'el', name: 'Greek', flag: '🇬🇷', locale: 'el-GR', articles: ['ο', 'η', 'το', 'οι', 'τα'] },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱', locale: 'he-IL', articles: ['ה'] },
  { code: 'vi', name: 'Vietnamese', flag: '🇻🇳', locale: 'vi-VN', articles: [] },
  { code: 'th', name: 'Thai', flag: '🇹🇭', locale: 'th-TH', articles: [] },
  { code: 'id', name: 'Indonesian', flag: '🇮🇩', locale: 'id-ID', articles: [] },
  { code: 'cs', name: 'Czech', flag: '🇨🇿', locale: 'cs-CZ', articles: ['ten', 'ta', 'to'] },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴', locale: 'nb-NO', articles: ['en', 'ei', 'et'] },
  { code: 'da', name: 'Danish', flag: '🇩🇰', locale: 'da-DK', articles: ['en', 'et'] },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮', locale: 'fi-FI', articles: [] },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦', locale: 'uk-UA', articles: [] },
  { code: 'ro', name: 'Romanian', flag: '🇷🇴', locale: 'ro-RO', articles: ['un', 'o'] },
  { code: 'hu', name: 'Hungarian', flag: '🇭🇺', locale: 'hu-HU', articles: ['a', 'az'] },
  { code: 'sw', name: 'Swahili', flag: '🇰🇪', locale: 'sw-KE', articles: [] },
  { code: 'bn', name: 'Bengali', flag: '🇧🇩', locale: 'bn-BD', articles: [] },
  { code: 'ta', name: 'Tamil', flag: '🇮🇳', locale: 'ta-IN', articles: [] },
  { code: 'pa', name: 'Punjabi', flag: '🇮🇳', locale: 'pa-IN', articles: [] },
  { code: 'kn', name: 'Kannada', flag: '🇮🇳', locale: 'kn-IN', articles: [] },
  { code: 'ms', name: 'Malay', flag: '🇲🇾', locale: 'ms-MY', articles: [] },
  { code: 'tl', name: 'Filipino (Tagalog)', flag: '🇵🇭', locale: 'fil-PH', articles: [] },
  { code: 'ca', name: 'Catalan', flag: '🇦🇩', locale: 'ca-ES', articles: ['el', 'la', 'els', 'les'] },
  { code: 'ga', name: 'Irish', flag: '🇮🇪', locale: 'ga-IE', articles: ['an', 'na'] },
  { code: 'cy', name: 'Welsh', flag: '🏴', locale: 'cy-GB', articles: ['y', 'yr', "'r"] },
  { code: 'eo', name: 'Esperanto', flag: '🌐', locale: 'eo', articles: ['la'] },
];

export const SUPPORTED_LANGUAGE_CODES = SUPPORTED_LANGUAGES.map(({ code }) => code);
export const languageByCode = (code) => SUPPORTED_LANGUAGES.find((item) => item.code === code);
